- name: adding nginx signing key
  apt_key:
    url: "https://nginx.org/keys/nginx_signing.key"
    state: present

- name: adding sources.list deb url for nginx
  apt_repository:
    repo: "deb https://nginx.org/packages/mainline/debian/ stretch nginx"
    state: present

- name: update the cache and install nginx server
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: updating customized templates for nginx configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"

  with_items:
    - { src: "templates/default.conf.j2", dst: "/etc/nginx/conf.d/default.conf" }    

  notify:
    - start nginx
    - startup nginx
