---
# handlers file for hidden-service
- name: restart tor
  service:
    name: tor
    state: restarted

- name: stop tor
  service:
    name: tor
    state: stopped

- name: restart monit
  service:
    name: monit
    state: restarted
